services:
  - type: web
    name: sky-soc
    env: static
    plan: free
    buildCommand: ""        # no build step needed
    staticPublishPath: .    # serve files from the root folder
    autoDeploy: true
